headers = {
    "Vitaldaten": ['Online erfasste Vitaldaten', 'Manuell erfasste Vitaldaten'],
    "Respiratordaten": ['Online erfasste Respiratorwerte', 'Beatmung', 'Manuell erfasste Respiratorwerte'],
    "Labor": [
        'Labor: Blutgase arteriell',
        'Labor: Blutgase venös',
        'Labor: Blutgase gv',
        'Labor: Blutgase unspez.',
        'Labor: Blutbild',
        'Labor: Differentialblutbild',
        'Labor: Blutgruppe',
        'Labor: Gerinnung',
        'Labor: TEG',
        'Labor: TAT',
        'Labor: Enzyme',
        'Labor: Retention',
        'Labor: Lipide',
        'Labor: Proteine',
        'Labor: Elektrolyte',
        'Labor: Blutzucker',
        'Labor: Klinische Chemie',
        'Labor: Medikamentenspiegel',
        'Labor: Schilddrüse',
        'Labor: Serologie/Infektion',
        ],
    "Dokumentation": ["Arztnotizen", "Pflegenotizen"],
    'Medikamentengaben': ["Medikamentengaben"],
    'Bilanz': ["Bilanz"],
    'Katheter': ["Katheter"],
    'Drainagen': ["Drainagen"],
    'Wunden': ["Wunden"],
    'ALLE Patientendaten': ["ALLE Patientendaten"]
}