name: Build Windows EXE (Conda)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-windows-conda:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          auto-update-conda: true
          python-version: '3.11'
          activate-environment: build-env

      - name: Install dependencies (pip inside conda env)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==5.13.0
        shell: bash

      - name: Create dist folder
        run: mkdir dist || echo "exists"

      - name: Build single-file EXE with PyInstaller (conda)
        run: |
          # Verwende app_launcher.py als Entry-Point
          pyinstaller --clean --onefile --name clean_mlife_app_conda --add-data "services;services" --add-data "med_examp.txt;." app_launcher.py
        shell: bash

      - name: List dist
        run: dir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe-clean-mlife-conda
          path: dist/clean_mlife_app_conda.exe
